feat: ui for filter
mathieumure/boomer-to-millenial pull request #16
Opened 2021-11-09 20:22 UTC by mathieumure

Fix #5

2021-11-10 18:20 UTC, jsulpis requested changes

2021-11-10 18:20 UTC, jsulpis commented on src/icon/Sort.icon.tsx
> +    <path
j'ai mis à jour l'icône sur Figma, tu peux le remplacer ici et mettre l'attribut fill du path à "currentColor" pour qu'il s'adapte à la propriété `color` de l'élément

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  transform: ${(props) => (props.reversed ? "rotate(180deg)" : "none")};
avec le nouvel icône tu pourras faire plutôt une symétrie verticale : 
`transform: matrix(1,0,0,-1,0,0);`

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  margin-top: 100px;
D'après mes essais `12vh` a l'air pas mal, ça devrait être plus responsive

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  margin-right: 12px;
`color: var(--grey-800);`

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  align-items: center;
`gap: 8px;`

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  transition: all 0.3s;
300ms me paraît long vu la taille de l'élément, je trouve ça mieux avec 200ms

2021-11-10 18:20 UTC, jsulpis commented on src/layout/Filters.tsx
> +  &:focus {
je mettrais pas l'état focus perso, parce que quand la souris sort du bouton après le clic ça reste grossi

2021-11-10 18:20 UTC, jsulpis commented on src/layout/MainContent.tsx
> +    setDescOrder(desc);
il manque un `flipRead();` ici

2021-11-10 18:55 UTC, mathieumure commented on src/layout/Filters.tsx
> +  &:focus {
ouais mais c'est plus accessible (si tu navigues avec les tab

2021-11-10 20:38 UTC, jsulpis commented on src/layout/Filters.tsx
> +  &:focus {
Peut-être mettre les box-shadow au focus comme j'ai fait sur le bouton poubelle si ça te va ?

2021-11-11 16:02 UTC, jsulpis approved these changes

2021-11-11 16:09 UTC, merged